services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    environment:
      VITE_BACKEND_URL: http://backend:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/postgres
      JWT_SECRET: mysecretkey
    ports:
      - "3001:3001"
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db-data: