version: '3.9'

services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:password@database:5432/mydb
      JWT_SECRET: mysecretkey
    ports:
      - "3001:3001"
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db-data: