CREATE TABLE Users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'employee')),
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Employees (
    id SERIAL PRIMARY KEY,
    hire_date DATE NOT NULL,
    name VARCHAR(50) NOT NULL,
    salary NUMERIC(10, 2) NOT NULL,
    user_id INT UNIQUE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Requests (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    summary VARCHAR(50) NOT NULL,
    employee_id INT NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES Employees(id)
);

INSERT INTO Users (email, password, role) VALUES
('admin@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'admin'),
('jdoe@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('jsmith@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('clopez@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('agarcia@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('lmartinez@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('mfernandez@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('jperez@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('lsanchez@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('pgomez@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee'),
('eruiz@example.com', '$2b$10$T2CeZYR6.tHiFxOtj.9O3ODLxgJ3gt7.CiRKjpnWs0fO.0FY4rGHi', 'employee');

INSERT INTO Employees (hire_date, name, salary, user_id) VALUES
('2018-01-15', 'Admin Admin', 50000.00, 1),
('2020-01-15', 'John Doe', 50000.00, 2),
('2021-07-22', 'Jane Smith', 60000.00, 3),
('2019-03-11', 'Carlos López', 55000.00, 4),
('2020-06-05', 'Ana García', 58000.00, 5),
('2021-09-19', 'Luis Martínez', 52000.00, 6),
('2022-01-03', 'María Fernández', 62000.00, 7),
('2018-11-23', 'José Pérez', 51000.00, 8),
('2019-07-10', 'Laura Sánchez', 49000.00, 9),
('2020-12-13', 'Pedro Gómez', 47000.00, 10),
('2021-05-25', 'Elena Ruiz', 53000.00, 11);

INSERT INTO Requests (code, description, summary, employee_id) VALUES
('REQ-001', 'Solicitud de equipo', 'Compra de laptop nueva', 2),
('REQ-002', 'Solicitud de capacitación', 'Curso avanzado en React', 2),
('REQ-003', 'Cambio de puesto', 'Ascenso a supervisor', 2),
('REQ-004', 'Vacaciones', 'Solicitud de 15 días', 2),
('REQ-005', 'Incremento salarial', 'Revisión de salario anual', 2),
('REQ-006', 'Equipo de oficina', 'Compra de silla ergonómica', 2),
('REQ-007', 'Cambio de horario', 'Solicitud de horario flexible', 2),
('REQ-008', 'Certificación técnica', 'Examen de certificación AWS', 2),
('REQ-009', 'Licencia médica', 'Ausencia por 10 días', 2),
('REQ-010', 'Capacitación interna', 'Taller de liderazgo', 2),
('REQ-011', 'Cambio de proyecto', 'Asignación a nuevo cliente', 2),
('REQ-012', 'Solicitud de recursos', 'Adquisición de software', 2),
('REQ-013', 'Equipo dañado', 'Reemplazo de monitor', 2),
('REQ-014', 'Ajuste salarial', 'Ajuste por inflación', 2),
('REQ-015', 'Reasignación de tareas', 'Cambio de responsabilidades', 2),
('REQ-016', 'Solicitud de equipo', 'Compra de laptop nueva', 3),
('REQ-017', 'Solicitud de capacitación', 'Curso avanzado en React', 3),
('REQ-018', 'Cambio de puesto', 'Ascenso a supervisor', 3),
('REQ-019', 'Vacaciones', 'Solicitud de 15 días', 3),
('REQ-020', 'Incremento salarial', 'Revisión de salario anual', 3),
('REQ-021', 'Equipo de oficina', 'Compra de silla ergonómica', 3),
('REQ-022', 'Cambio de horario', 'Solicitud de horario flexible', 3),
('REQ-023', 'Certificación técnica', 'Examen de certificación AWS', 3),
('REQ-024', 'Licencia médica', 'Ausencia por 10 días', 3),
('REQ-025', 'Capacitación interna', 'Taller de liderazgo', 3),
('REQ-026', 'Cambio de proyecto', 'Asignación a nuevo cliente', 3),
('REQ-027', 'Solicitud de recursos', 'Adquisición de software', 3),
('REQ-028', 'Equipo dañado', 'Reemplazo de monitor', 3),
('REQ-029', 'Ajuste salarial', 'Ajuste por inflación', 3),
('REQ-030', 'Reasignación de tareas', 'Cambio de responsabilidades', 3),
('REQ-031', 'Solicitud de equipo', 'Compra de laptop nueva', 4),
('REQ-032', 'Solicitud de capacitación', 'Curso avanzado en React', 4),
('REQ-033', 'Cambio de puesto', 'Ascenso a supervisor', 4),
('REQ-034', 'Vacaciones', 'Solicitud de 15 días', 4),
('REQ-035', 'Incremento salarial', 'Revisión de salario anual', 4),
('REQ-036', 'Equipo de oficina', 'Compra de silla ergonómica', 4),
('REQ-037', 'Cambio de horario', 'Solicitud de horario flexible', 4),
('REQ-038', 'Certificación técnica', 'Examen de certificación AWS', 4),
('REQ-039', 'Licencia médica', 'Ausencia por 10 días', 4),
('REQ-040', 'Capacitación interna', 'Taller de liderazgo', 4),
('REQ-041', 'Cambio de proyecto', 'Asignación a nuevo cliente', 4),
('REQ-042', 'Solicitud de recursos', 'Adquisición de software', 4),
('REQ-043', 'Equipo dañado', 'Reemplazo de monitor', 4),
('REQ-044', 'Ajuste salarial', 'Ajuste por inflación', 4),
('REQ-045', 'Reasignación de tareas', 'Cambio de responsabilidades', 4),
('REQ-046', 'Solicitud de equipo', 'Compra de laptop nueva', 5),
('REQ-047', 'Solicitud de capacitación', 'Curso avanzado en React', 5),
('REQ-048', 'Cambio de puesto', 'Ascenso a supervisor', 5),
('REQ-049', 'Vacaciones', 'Solicitud de 15 días', 5),
('REQ-050', 'Incremento salarial', 'Revisión de salario anual', 5),
('REQ-051', 'Equipo de oficina', 'Compra de silla ergonómica', 5),
('REQ-052', 'Cambio de horario', 'Solicitud de horario flexible', 5),
('REQ-053', 'Certificación técnica', 'Examen de certificación AWS', 5),
('REQ-054', 'Licencia médica', 'Ausencia por 10 días', 5),
('REQ-055', 'Capacitación interna', 'Taller de liderazgo', 5),
('REQ-056', 'Cambio de proyecto', 'Asignación a nuevo cliente', 5),
('REQ-057', 'Solicitud de recursos', 'Adquisición de software', 5),
('REQ-058', 'Equipo dañado', 'Reemplazo de monitor', 5),
('REQ-059', 'Ajuste salarial', 'Ajuste por inflación', 5),
('REQ-060', 'Reasignación de tareas', 'Cambio de responsabilidades', 5),
('REQ-061', 'Solicitud de equipo', 'Compra de laptop nueva', 6),
('REQ-062', 'Solicitud de capacitación', 'Curso avanzado en React', 6),
('REQ-063', 'Cambio de puesto', 'Ascenso a supervisor', 6),
('REQ-064', 'Vacaciones', 'Solicitud de 15 días', 6),
('REQ-065', 'Incremento salarial', 'Revisión de salario anual', 6),
('REQ-066', 'Equipo de oficina', 'Compra de silla ergonómica', 6),
('REQ-067', 'Cambio de horario', 'Solicitud de horario flexible', 6),
('REQ-068', 'Certificación técnica', 'Examen de certificación AWS', 6),
('REQ-069', 'Licencia médica', 'Ausencia por 10 días', 6),
('REQ-070', 'Capacitación interna', 'Taller de liderazgo', 6),
('REQ-071', 'Cambio de proyecto', 'Asignación a nuevo cliente', 6),
('REQ-072', 'Solicitud de recursos', 'Adquisición de software', 6),
('REQ-073', 'Equipo dañado', 'Reemplazo de monitor', 6),
('REQ-074', 'Ajuste salarial', 'Ajuste por inflación', 6),
('REQ-075', 'Reasignación de tareas', 'Cambio de responsabilidades', 6),
('REQ-076', 'Solicitud de equipo', 'Compra de laptop nueva', 7),
('REQ-077', 'Solicitud de capacitación', 'Curso avanzado en React', 7),
('REQ-078', 'Cambio de puesto', 'Ascenso a supervisor', 7),
('REQ-079', 'Vacaciones', 'Solicitud de 15 días', 7),
('REQ-080', 'Incremento salarial', 'Revisión de salario anual', 7),
('REQ-081', 'Equipo de oficina', 'Compra de silla ergonómica', 7),
('REQ-082', 'Cambio de horario', 'Solicitud de horario flexible', 7),
('REQ-083', 'Certificación técnica', 'Examen de certificación AWS', 7),
('REQ-084', 'Licencia médica', 'Ausencia por 10 días', 7),
('REQ-085', 'Capacitación interna', 'Taller de liderazgo', 7),
('REQ-086', 'Cambio de proyecto', 'Asignación a nuevo cliente', 7),
('REQ-087', 'Solicitud de recursos', 'Adquisición de software', 7),
('REQ-088', 'Equipo dañado', 'Reemplazo de monitor', 7),
('REQ-089', 'Ajuste salarial', 'Ajuste por inflación', 7),
('REQ-090', 'Reasignación de tareas', 'Cambio de responsabilidades', 7),
('REQ-091', 'Solicitud de equipo', 'Compra de laptop nueva', 8),
('REQ-092', 'Solicitud de capacitación', 'Curso avanzado en React', 8),
('REQ-093', 'Cambio de puesto', 'Ascenso a supervisor', 8),
('REQ-094', 'Vacaciones', 'Solicitud de 15 días', 8),
('REQ-095', 'Incremento salarial', 'Revisión de salario anual', 8),
('REQ-096', 'Equipo de oficina', 'Compra de silla ergonómica', 8),
('REQ-097', 'Cambio de horario', 'Solicitud de horario flexible', 8),
('REQ-098', 'Certificación técnica', 'Examen de certificación AWS', 8),
('REQ-099', 'Licencia médica', 'Ausencia por 10 días', 8),
('REQ-100', 'Capacitación interna', 'Taller de liderazgo', 8),
('REQ-101', 'Cambio de proyecto', 'Asignación a nuevo cliente', 8),
('REQ-102', 'Solicitud de recursos', 'Adquisición de software', 8),
('REQ-103', 'Equipo dañado', 'Reemplazo de monitor', 8),
('REQ-104', 'Ajuste salarial', 'Ajuste por inflación', 8),
('REQ-105', 'Reasignación de tareas', 'Cambio de responsabilidades', 8),
('REQ-106', 'Solicitud de equipo', 'Compra de laptop nueva', 9),
('REQ-107', 'Solicitud de capacitación', 'Curso avanzado en React', 9),
('REQ-108', 'Cambio de puesto', 'Ascenso a supervisor', 9),
('REQ-109', 'Vacaciones', 'Solicitud de 15 días', 9),
('REQ-110', 'Incremento salarial', 'Revisión de salario anual', 9),
('REQ-111', 'Equipo de oficina', 'Compra de silla ergonómica', 9),
('REQ-112', 'Cambio de horario', 'Solicitud de horario flexible', 9),
('REQ-113', 'Certificación técnica', 'Examen de certificación AWS', 9),
('REQ-114', 'Licencia médica', 'Ausencia por 10 días', 9),
('REQ-115', 'Capacitación interna', 'Taller de liderazgo', 9),
('REQ-116', 'Cambio de proyecto', 'Asignación a nuevo cliente', 9),
('REQ-117', 'Solicitud de recursos', 'Adquisición de software', 9),
('REQ-118', 'Equipo dañado', 'Reemplazo de monitor', 9),
('REQ-119', 'Ajuste salarial', 'Ajuste por inflación', 9),
('REQ-120', 'Reasignación de tareas', 'Cambio de responsabilidades', 9),
('REQ-121', 'Solicitud de equipo', 'Compra de laptop nueva', 10),
('REQ-122', 'Solicitud de capacitación', 'Curso avanzado en React', 10),
('REQ-123', 'Cambio de puesto', 'Ascenso a supervisor', 10),
('REQ-124', 'Vacaciones', 'Solicitud de 15 días', 10),
('REQ-125', 'Incremento salarial', 'Revisión de salario anual', 10),
('REQ-126', 'Equipo de oficina', 'Compra de silla ergonómica', 10),
('REQ-127', 'Cambio de horario', 'Solicitud de horario flexible', 10),
('REQ-128', 'Certificación técnica', 'Examen de certificación AWS', 10),
('REQ-129', 'Licencia médica', 'Ausencia por 10 días', 10),
('REQ-130', 'Capacitación interna', 'Taller de liderazgo', 10),
('REQ-131', 'Cambio de proyecto', 'Asignación a nuevo cliente', 10),
('REQ-132', 'Solicitud de recursos', 'Adquisición de software', 10),
('REQ-133', 'Equipo dañado', 'Reemplazo de monitor', 10),
('REQ-134', 'Ajuste salarial', 'Ajuste por inflación', 10),
('REQ-135', 'Reasignación de tareas', 'Cambio de responsabilidades', 10),
('REQ-136', 'Solicitud de equipo', 'Compra de laptop nueva', 11),
('REQ-137', 'Solicitud de capacitación', 'Curso avanzado en React', 11),
('REQ-138', 'Cambio de puesto', 'Ascenso a supervisor', 11),
('REQ-139', 'Vacaciones', 'Solicitud de 15 días', 11),
('REQ-140', 'Incremento salarial', 'Revisión de salario anual', 11),
('REQ-141', 'Equipo de oficina', 'Compra de silla ergonómica', 11),
('REQ-142', 'Cambio de horario', 'Solicitud de horario flexible', 11),
('REQ-143', 'Certificación técnica', 'Examen de certificación AWS', 11),
('REQ-144', 'Licencia médica', 'Ausencia por 10 días', 11),
('REQ-145', 'Capacitación interna', 'Taller de liderazgo', 11),
('REQ-146', 'Cambio de proyecto', 'Asignación a nuevo cliente', 11),
('REQ-147', 'Solicitud de recursos', 'Adquisición de software', 11),
('REQ-148', 'Equipo dañado', 'Reemplazo de monitor', 11),
('REQ-149', 'Ajuste salarial', 'Ajuste por inflación', 11),
('REQ-150', 'Reasignación de tareas', 'Cambio de responsabilidades', 11);